### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by moltar** [oleg-koval/excel-date-to-js#16]
Here's a type that works, if you want to add it to the project:

```ts
declare module "excel-date-to-js" {
  export function getJsDateFromExcel(excelDate: number): Date
}
```

You can just create an `index.d.ts` file in the root, and put that there.

Thanks.

**Comment by oleg-koval** [comment]
Thanks! included in https://github.com/oleg-koval/excel-date-to-js/commit/38fa0d4a3393f088553ccca007033be12171e17f
